### ISSUE TITLE
Understanding sleep

### ISSUE THREAD

**Issue by PatrickCoyle** [nooreendabbish/Traffic#9]
We cannot know a driver's sleep behavior directly from the GES data, but the National Sleep Foundation does an annual survey to study the demography of sleep and sleep-related topics:

https://sleepfoundation.org/sleep-polls

I've only looked at the 2014 questionnaire, which does not appear to involve any geographically specific self-report. I'll keep looking. Ultimately, I would like to be able to evaluate the connection between regional sleep behaviors and regional drowsy driving prevalence, if valid.

**Comment by nooreendabbish** [comment]
Do you have evidence that there is a regional difference?

**Comment by PatrickCoyle** [comment]
No. I've just begun to look around for sleep data. It's probably more likely to be a matter of socioeconomic status, so we could possibly tie it to ZIP code like Nastya did, but I doubt we'd find significant differences between states.

This is sort of a half-baked issue at this point but I think it is important for us to at least read about the demographics of sleep, even if we don't include it in our modeling. I know that if I were an attendee viewing our poster, that's the exact type of question I would ask!

**Comment by PatrickCoyle** [comment]
Closed for inactivity
